#!/usr/bin/env bash
# (c) JFrog Ltd. (2026)
# Tests for scripts/generate-evidence.sh: the subject-path naming and the
# collect_* opt-out / warning branches of the orchestration. generate() is
# stubbed so no collectors or the JFrog CLI run - only the dispatch is exercised.
set -uo pipefail

TESTS_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
REPO_ROOT="$(cd -- "${TESTS_DIR}/.." &>/dev/null && pwd)"

# shellcheck source=./lib/test_helpers.sh
source "${TESTS_DIR}/lib/test_helpers.sh"

export GITHUB_REPOSITORY="acme/widget"
export MERGE_COMMIT_SHA="abcdef1234567890"

# Source generate-evidence.sh in a subshell (so its `set -e` and the
# executed-directly guard don't leak into the harness) and print the subject
# path for one evidence type.
subject_path() {
  (
    # shellcheck source=../scripts/generate-evidence.sh
    source "${REPO_ROOT}/scripts/generate-evidence.sh"
    evidence_subject_path "$1"
  )
}

# Run main() with generate() stubbed to just announce the type it would build,
# so the branch logic is testable without collectors or jf. Empty args leave the
# corresponding collect_* env unset (to exercise the default).
run_main() {
  local bp="$1" pr="$2"
  (
    [[ -n "$bp" ]] && export COLLECT_BRANCH_PROTECTION="$bp"
    [[ -n "$pr" ]] && export COLLECT_PULL_REQUEST_MERGE="$pr"
    # shellcheck source=../scripts/generate-evidence.sh
    source "${REPO_ROOT}/scripts/generate-evidence.sh"
    generate() { echo "GENERATE:$1"; }
    main
  ) 2>&1
}

test_subject_path_uses_owner_type_and_short_sha() {
  assert_equal "git-evidence/branch-protection/acme-branch-protection-abcdef12.json" \
    "$(subject_path branch-protection)" "branch-protection subject path" || return 1
  assert_equal "git-evidence/pull-request-merge/acme-pull-request-merge-abcdef12.json" \
    "$(subject_path pull-request-merge)" "pull-request-merge subject path"
}

test_both_disabled_warns_and_generates_nothing() {
  local out
  out="$(run_main false false)"
  assert_contains "$out" "::warning::Both evidence types are disabled" "both-disabled warning is emitted" || return 1
  assert_contains "$out" "Skipping branch-protection evidence" "branch-protection skip message" || return 1
  assert_contains "$out" "Skipping pull-request-merge evidence" "pull-request-merge skip message" || return 1
  assert_not_contains "$out" "GENERATE:" "no evidence type is generated when both are disabled"
}

test_only_branch_protection_generates_bp_and_skips_pr() {
  local out
  out="$(run_main true false)"
  assert_contains "$out" "GENERATE:branch-protection" "branch-protection is generated" || return 1
  assert_not_contains "$out" "GENERATE:pull-request-merge" "pull-request-merge is not generated" || return 1
  assert_contains "$out" "Skipping pull-request-merge evidence" "pull-request-merge skip message" || return 1
  assert_not_contains "$out" "::warning::Both evidence types are disabled" "no both-disabled warning when one is enabled"
}

test_only_pull_request_merge_generates_pr_and_skips_bp() {
  local out
  out="$(run_main false true)"
  assert_contains "$out" "GENERATE:pull-request-merge" "pull-request-merge is generated" || return 1
  assert_not_contains "$out" "GENERATE:branch-protection" "branch-protection is not generated" || return 1
  assert_contains "$out" "Skipping branch-protection evidence" "branch-protection skip message"
}

test_default_generates_both() {
  local out
  out="$(run_main "" "")"
  assert_contains "$out" "GENERATE:branch-protection" "branch-protection generated by default" || return 1
  assert_contains "$out" "GENERATE:pull-request-merge" "pull-request-merge generated by default" || return 1
  assert_not_contains "$out" "Skipping" "nothing is skipped by default"
}

run_test test_subject_path_uses_owner_type_and_short_sha
run_test test_both_disabled_warns_and_generates_nothing
run_test test_only_branch_protection_generates_bp_and_skips_pr
run_test test_only_pull_request_merge_generates_pr_and_skips_bp
run_test test_default_generates_both

report_results
